version: "3"
services:
  database:
    image: 'mongo'
    container_name: "sample_mongo"
    environment:
      - MONGO_INITDB_DATABASE="sample-journal"
      - MONGO_INITDB_ROOT_USERNAME="surya"
      - MONGO_INITDB_ROOT_PASSWORD="surya"
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:rw
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"